import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Dialog {
    id: dialog
    modal: true
    anchors.centerIn: Overlay.overlay
    width: 700
    padding: 0
    background: Rectangle { color: "#152238"; radius: 14; border.color: "#2A4266" }
    header: RowLayout { height: 68; Label { Layout.leftMargin: 24; Layout.fillWidth: true; text: qsTr("Settings"); color: "#F1F6FF"; font.pixelSize: 19; font.weight: Font.DemiBold } ToolButton { Layout.rightMargin: 16; text: "×"; font.pixelSize: 22; onClicked: dialog.close() } }
    contentItem: GridLayout { columns: 2; width: dialog.width - 48; columnSpacing: 24; rowSpacing: 20
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Appearance"); color: "#C9D5E8"; font.weight: Font.DemiBold } Label { text: qsTr("Theme"); color: "#8C9AB0"; font.pixelSize: 11 } ComboBox { Layout.fillWidth: true; model: ["system", "dark", "light"]; currentIndex: Math.max(0, model.indexOf(settingsService.theme)); onActivated: settingsService.setTheme(currentText) } Label { text: qsTr("Density"); color: "#8C9AB0"; font.pixelSize: 11 } ComboBox { Layout.fillWidth: true; model: ["comfortable", "compact"]; currentIndex: Math.max(0, model.indexOf(settingsService.density)); onActivated: settingsService.setDensity(currentText) } }
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Language and direction"); color: "#C9D5E8"; font.weight: Font.DemiBold } Label { text: qsTr("Interface language"); color: "#8C9AB0"; font.pixelSize: 11 } ComboBox { Layout.fillWidth: true; model: ["en", "ar", "de", "he", "fa"]; currentIndex: Math.max(0, model.indexOf(settingsService.language)); onActivated: settingsService.setLanguage(currentText) } Label { text: settingsService.rightToLeft ? qsTr("Right-to-left layout enabled") : qsTr("Left-to-right layout enabled"); color: "#78C8A9"; font.pixelSize: 11 } }
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Core profile and bandwidth"); color: "#C9D5E8"; font.weight: Font.DemiBold } ComboBox { id: profileSelector; Layout.fillWidth: true; model: taskController.profiles; textRole: "name"; valueRole: "id"; currentIndex: Math.max(0, indexOfValue(taskController.activeProfile)); onActivated: taskController.setActiveProfile(currentValue) } RowLayout { Layout.fillWidth: true; SpinBox { id: globalLimit; from: 0; to: 1000000; value: taskController.bandwidth.globalLimitKbps || taskController.bandwidth.global_limit_kbps || 0; editable: true; Layout.fillWidth: true } Button { text: qsTr("Apply KB/s"); onClicked: taskController.setBandwidthLimit(globalLimit.value) } } }
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Core retry policy"); color: "#C9D5E8"; font.weight: Font.DemiBold } ComboBox { id: retryPreset; Layout.fillWidth: true; model: ["default", "aggressive", "conservative", "none"] } RowLayout { Layout.fillWidth: true; Button { text: qsTr("Apply preset"); onClicked: taskController.setRetryPolicyPreset(retryPreset.currentText) } Label { Layout.fillWidth: true; text: qsTr("Retries: ") + (taskController.retryPolicy.maxRetries || taskController.retryPolicy.max_retries || "—"); color: "#78879E"; font.pixelSize: 11; horizontalAlignment: Text.AlignRight } } }
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Notifications"); color: "#C9D5E8"; font.weight: Font.DemiBold } CheckBox { text: qsTr("Notify for Core state changes"); checked: settingsService.notificationsEnabled; onToggled: settingsService.setNotificationsEnabled(checked) } Label { text: qsTr("Completion, failure, pause and resume are de-duplicated through native desktop notifications."); color: "#78879E"; font.pixelSize: 11; wrapMode: Text.Wrap } }
        ColumnLayout { Layout.fillWidth: true; Label { text: qsTr("Integration and diagnostics"); color: "#C9D5E8"; font.weight: Font.DemiBold } Label { Layout.fillWidth: true; text: taskController.browserHealth.status || qsTr("Browser bridge health is available on the Browser page."); color: "#78879E"; font.pixelSize: 11; wrapMode: Text.Wrap } Label { Layout.fillWidth: true; text: qsTr("Logs, capability details and task traces are available on Diagnostics."); color: "#78879E"; font.pixelSize: 11; wrapMode: Text.Wrap } }
        Label { Layout.columnSpan: 2; Layout.fillWidth: true; text: qsTr("NDM2 exposes only settings with an observable local or authenticated Core effect. Browser extension installation, media options and unsupported legacy-only controls remain owned by their existing components."); wrapMode: Text.Wrap; color: "#8390A4"; font.pixelSize: 11 }
    }
}
